# Generated by Django 5.1.6 on 2025-05-22 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0001_initial'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='product',
            field=models.ManyToManyField(related_name='discount', to='product.product'),
        ),
    ]
