# Generated by Django 5.1.6 on 2025-05-22 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0002_alter_discount_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discount',
            old_name='product',
            new_name='products',
        ),
    ]
