# Generated by Django 5.1.6 on 2025-02-18 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productvariant',
            old_name='quantity',
            new_name='stock',
        ),
    ]
