# Generated by Django 5.1.6 on 2025-02-19 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_qty',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
