# Generated by Django 5.1.6 on 2025-06-13 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_order_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='retailer',
        ),
    ]
